USE EFQueryDB
GO

INSERT INTO [dbo].[Country] Values ('Afghanistan')
INSERT INTO [dbo].[Country] Values ('Albania')
INSERT INTO [dbo].[Country] Values ('Algeria')
INSERT INTO [dbo].[Country] Values ('Andorra')
INSERT INTO [dbo].[Country] Values ('Angola')
INSERT INTO [dbo].[Country] Values ('Antigua and Barbuda')
INSERT INTO [dbo].[Country] Values ('Argentina')
INSERT INTO [dbo].[Country] Values ('Armenia')
INSERT INTO [dbo].[Country] Values ('Australia')
INSERT INTO [dbo].[Country] Values ('Austria')
INSERT INTO [dbo].[Country] Values ('Azerbaijan')
INSERT INTO [dbo].[Country] Values ('Bahamas')
INSERT INTO [dbo].[Country] Values ('Bahrain')
INSERT INTO [dbo].[Country] Values ('Bangladesh')
INSERT INTO [dbo].[Country] Values ('Barbados')
INSERT INTO [dbo].[Country] Values ('Belarus')
INSERT INTO [dbo].[Country] Values ('Belgium')
INSERT INTO [dbo].[Country] Values ('Belize')
INSERT INTO [dbo].[Country] Values ('Benin')
INSERT INTO [dbo].[Country] Values ('Bhutan')
INSERT INTO [dbo].[Country] Values ('Bolivia')
INSERT INTO [dbo].[Country] Values ('Bosnia and Herzegovina')
INSERT INTO [dbo].[Country] Values ('Botswana')
INSERT INTO [dbo].[Country] Values ('Brazil')
INSERT INTO [dbo].[Country] Values ('Brunei')
INSERT INTO [dbo].[Country] Values ('Bulgaria')
INSERT INTO [dbo].[Country] Values ('Burkina Faso')
INSERT INTO [dbo].[Country] Values ('Burundi')
INSERT INTO [dbo].[Country] Values ('Côte dIvoire')
INSERT INTO [dbo].[Country] Values ('Cabo Verde')
INSERT INTO [dbo].[Country] Values ('Cambodia')
INSERT INTO [dbo].[Country] Values ('Cameroon')
INSERT INTO [dbo].[Country] Values ('Canada')
INSERT INTO [dbo].[Country] Values ('Central')
INSERT INTO [dbo].[Country] Values ('Chad')
INSERT INTO [dbo].[Country] Values ('Chile')
INSERT INTO [dbo].[Country] Values ('China')
INSERT INTO [dbo].[Country] Values ('Colombia')
INSERT INTO [dbo].[Country] Values ('Comoros')
INSERT INTO [dbo].[Country] Values ('Congo (Congo-Brazzaville)')
INSERT INTO [dbo].[Country] Values ('Costa Rica')
INSERT INTO [dbo].[Country] Values ('Croatia')
INSERT INTO [dbo].[Country] Values ('Cuba')
INSERT INTO [dbo].[Country] Values ('Cyprus')
INSERT INTO [dbo].[Country] Values ('Czechia (Czech Republic)')
INSERT INTO [dbo].[Country] Values ('Democratic Republic of the Congo')
INSERT INTO [dbo].[Country] Values ('Denmark')
INSERT INTO [dbo].[Country] Values ('Djibouti')
INSERT INTO [dbo].[Country] Values ('Dominica')
INSERT INTO [dbo].[Country] Values ('Dominican Republic')
INSERT INTO [dbo].[Country] Values ('Ecuador')
INSERT INTO [dbo].[Country] Values ('Egypt')
INSERT INTO [dbo].[Country] Values ('El Salvador')
INSERT INTO [dbo].[Country] Values ('Equatorial Guinea')
INSERT INTO [dbo].[Country] Values ('Eritrea')
INSERT INTO [dbo].[Country] Values ('Estonia')
INSERT INTO [dbo].[Country] Values ('Eswatini (fmr. "Swaziland")')
INSERT INTO [dbo].[Country] Values ('Ethiopia')
INSERT INTO [dbo].[Country] Values ('Fiji')
INSERT INTO [dbo].[Country] Values ('Finland')
INSERT INTO [dbo].[Country] Values ('France')
INSERT INTO [dbo].[Country] Values ('Gabon')
INSERT INTO [dbo].[Country] Values ('Gambia')
INSERT INTO [dbo].[Country] Values ('Georgia')
INSERT INTO [dbo].[Country] Values ('Germany')
INSERT INTO [dbo].[Country] Values ('Ghana')
INSERT INTO [dbo].[Country] Values ('Greece')
INSERT INTO [dbo].[Country] Values ('Grenada')
INSERT INTO [dbo].[Country] Values ('Guatemala')
INSERT INTO [dbo].[Country] Values ('Guinea')
INSERT INTO [dbo].[Country] Values ('Guinea-Bissau')
INSERT INTO [dbo].[Country] Values ('Guyana')
INSERT INTO [dbo].[Country] Values ('Haiti')
INSERT INTO [dbo].[Country] Values ('Holy See')
INSERT INTO [dbo].[Country] Values ('Honduras')
INSERT INTO [dbo].[Country] Values ('Hungary')
INSERT INTO [dbo].[Country] Values ('Iceland')
INSERT INTO [dbo].[Country] Values ('India')
INSERT INTO [dbo].[Country] Values ('Indonesia')
INSERT INTO [dbo].[Country] Values ('Iran')
INSERT INTO [dbo].[Country] Values ('Iraq')
INSERT INTO [dbo].[Country] Values ('Ireland')
INSERT INTO [dbo].[Country] Values ('Israel')
INSERT INTO [dbo].[Country] Values ('Italy')
INSERT INTO [dbo].[Country] Values ('Jamaica')
INSERT INTO [dbo].[Country] Values ('Japan')
INSERT INTO [dbo].[Country] Values ('Jordan')
INSERT INTO [dbo].[Country] Values ('Kazakhstan')
INSERT INTO [dbo].[Country] Values ('Kenya')
INSERT INTO [dbo].[Country] Values ('Kiribati')
INSERT INTO [dbo].[Country] Values ('Kuwait')
INSERT INTO [dbo].[Country] Values ('Kyrgyzstan')
INSERT INTO [dbo].[Country] Values ('Laos')
INSERT INTO [dbo].[Country] Values ('Latvia')
INSERT INTO [dbo].[Country] Values ('Lebanon')
INSERT INTO [dbo].[Country] Values ('Lesotho')
INSERT INTO [dbo].[Country] Values ('Liberia')
INSERT INTO [dbo].[Country] Values ('Libya')
INSERT INTO [dbo].[Country] Values ('Liechtenstein')
INSERT INTO [dbo].[Country] Values ('Lithuania')
INSERT INTO [dbo].[Country] Values ('Luxembourg')
INSERT INTO [dbo].[Country] Values ('Madagascar')
INSERT INTO [dbo].[Country] Values ('Malawi')
INSERT INTO [dbo].[Country] Values ('Malaysia')
INSERT INTO [dbo].[Country] Values ('Maldives')
INSERT INTO [dbo].[Country] Values ('Mali')
INSERT INTO [dbo].[Country] Values ('Malta')
INSERT INTO [dbo].[Country] Values ('Marshall Islands')
INSERT INTO [dbo].[Country] Values ('Mauritania')
INSERT INTO [dbo].[Country] Values ('Mauritius')
INSERT INTO [dbo].[Country] Values ('Mexico')
INSERT INTO [dbo].[Country] Values ('Micronesia')
INSERT INTO [dbo].[Country] Values ('Moldova')
INSERT INTO [dbo].[Country] Values ('Monaco')
INSERT INTO [dbo].[Country] Values ('Mongolia')
INSERT INTO [dbo].[Country] Values ('Montenegro')
INSERT INTO [dbo].[Country] Values ('Morocco')
INSERT INTO [dbo].[Country] Values ('Mozambique')
INSERT INTO [dbo].[Country] Values ('Myanmar (formerly Burma)')
INSERT INTO [dbo].[Country] Values ('Namibia')
INSERT INTO [dbo].[Country] Values ('Nauru')
INSERT INTO [dbo].[Country] Values ('Nepal')
INSERT INTO [dbo].[Country] Values ('Netherlands')
INSERT INTO [dbo].[Country] Values ('New Zealand')
INSERT INTO [dbo].[Country] Values ('Nicaragua')
INSERT INTO [dbo].[Country] Values ('Niger')
INSERT INTO [dbo].[Country] Values ('Nigeria')
INSERT INTO [dbo].[Country] Values ('North Korea')
INSERT INTO [dbo].[Country] Values ('North Macedonia')
INSERT INTO [dbo].[Country] Values ('Norway')
INSERT INTO [dbo].[Country] Values ('Oman')
INSERT INTO [dbo].[Country] Values ('Pakistan')
INSERT INTO [dbo].[Country] Values ('Palau')
INSERT INTO [dbo].[Country] Values ('Palestine State')
INSERT INTO [dbo].[Country] Values ('Panama')
INSERT INTO [dbo].[Country] Values ('Papua New Guinea')
INSERT INTO [dbo].[Country] Values ('Paraguay')
INSERT INTO [dbo].[Country] Values ('Peru')
INSERT INTO [dbo].[Country] Values ('Philippines')
INSERT INTO [dbo].[Country] Values ('Poland')
INSERT INTO [dbo].[Country] Values ('Portugal')
INSERT INTO [dbo].[Country] Values ('Qatar')
INSERT INTO [dbo].[Country] Values ('Romania')
INSERT INTO [dbo].[Country] Values ('Russia')
INSERT INTO [dbo].[Country] Values ('Rwanda')
INSERT INTO [dbo].[Country] Values ('Saint Kitts and Nevis')
INSERT INTO [dbo].[Country] Values ('Saint Lucia')
INSERT INTO [dbo].[Country] Values ('Saint Vincent and the Grenadines')
INSERT INTO [dbo].[Country] Values ('Samoa')
INSERT INTO [dbo].[Country] Values ('San Marino')
INSERT INTO [dbo].[Country] Values ('Sao Tome and Principe')
INSERT INTO [dbo].[Country] Values ('Saudi Arabia')
INSERT INTO [dbo].[Country] Values ('Senegal')
INSERT INTO [dbo].[Country] Values ('Serbia')
INSERT INTO [dbo].[Country] Values ('Seychelles')
INSERT INTO [dbo].[Country] Values ('Sierra Leone')
INSERT INTO [dbo].[Country] Values ('Singapore')
INSERT INTO [dbo].[Country] Values ('Slovakia')
INSERT INTO [dbo].[Country] Values ('Slovenia')
INSERT INTO [dbo].[Country] Values ('Solomon Islands')
INSERT INTO [dbo].[Country] Values ('Somalia')
INSERT INTO [dbo].[Country] Values ('South Africa')
INSERT INTO [dbo].[Country] Values ('South Korea')
INSERT INTO [dbo].[Country] Values ('South Sudan')
INSERT INTO [dbo].[Country] Values ('Spain')
INSERT INTO [dbo].[Country] Values ('Sri Lanka')
INSERT INTO [dbo].[Country] Values ('Sudan')
INSERT INTO [dbo].[Country] Values ('Suriname')
INSERT INTO [dbo].[Country] Values ('Sweden')
INSERT INTO [dbo].[Country] Values ('Switzerland')
INSERT INTO [dbo].[Country] Values ('Syria')
INSERT INTO [dbo].[Country] Values ('Tajikistan')
INSERT INTO [dbo].[Country] Values ('Tanzania')
INSERT INTO [dbo].[Country] Values ('Thailand')
INSERT INTO [dbo].[Country] Values ('Timor-Leste')
INSERT INTO [dbo].[Country] Values ('Togo')
INSERT INTO [dbo].[Country] Values ('Tonga')
INSERT INTO [dbo].[Country] Values ('Trinidad and Tobago')
INSERT INTO [dbo].[Country] Values ('Tunisia')
INSERT INTO [dbo].[Country] Values ('Turkey')
INSERT INTO [dbo].[Country] Values ('Turkmenistan')
INSERT INTO [dbo].[Country] Values ('Tuvalu')
INSERT INTO [dbo].[Country] Values ('Uganda')
INSERT INTO [dbo].[Country] Values ('Ukraine')
INSERT INTO [dbo].[Country] Values ('United Arab Emirates')
INSERT INTO [dbo].[Country] Values ('United Kingdom')
INSERT INTO [dbo].[Country] Values ('United States of America')
INSERT INTO [dbo].[Country] Values ('Uruguay')
INSERT INTO [dbo].[Country] Values ('Uzbekistan')
INSERT INTO [dbo].[Country] Values ('Vanuatu')
INSERT INTO [dbo].[Country] Values ('Venezuela')
INSERT INTO [dbo].[Country] Values ('Vietnam')
INSERT INTO [dbo].[Country] Values ('Yemen')
INSERT INTO [dbo].[Country] Values ('Zambia')
INSERT INTO [dbo].[Country] Values ('Zimbabwe')